### ISSUE TITLE
Allow setting the update interval

### ISSUE THREAD

**Issue by secretmango** [tonywalker1/silverblue-update#1]
Really nice script! It works pretty well. 

But I have the feeling daily updates slow down the system too much, some solution has to be found.

Windows does this with the "absense time". Maybe thats a good idea too, but also dont know how to integrate that as a systemd timer. Or maybe just weekly? Or every 3 days?

**Comment by tonywalker1** [comment]
Good suggestion and I will add that to the next version. In the meantime, you can change the timer yourself...

Open ```/etc/systemd/system/silverblue-update.timer``` in the editor of your choice.  You will see two line in that file which control the systemd timer. 

```
OnUnitActiveSec=22hr
RandomizedDelaySec=4h
```

Change the ```OnUnitActiveSec``` entry to a value that works for you. For example,
```OnUnitActiveSec=72hr``` for every three days or ```OnUnitActiveSec-1w``` for one week.

After that, disable and re-enable the timer as follows: ```systemctl daemon-reload```

Let me know if that works for your immediate need. I will make the change relatively soon!

Thank you! I am glad the script is helping you.

**Comment by secretmango** [comment]
Thanks! seems to work. I integrate your script in our "[rpm-ostree setup script](https://github.com/iaacornus/Fedora-OSTree-Setup)", saves a lot of work and works perfectly!

**Comment by tonywalker1** [comment]
Thanks for the suggestion! Addressing with better documentation...
